title: 修士論文テンプレート
author: 柴田 侃汰
copyright: "2023"

execute:
  execute_notebooks: 'off'

# HTML-specific settings
html:
  google_analytics_id       : "G-5LBYFFM18Y"
  announcement: "最終的なテンプレートの仕上がりは<a href='https://drive.google.com/file/d/1jn7SQ_-rVKIgPA9TD3b5PmZf3F-u__ze/view?usp=share_link'>こちら(pdf)</a>．LaTeXファイル群は<a href='https://drive.google.com/file/d/1dSi6wrrV3YI5Dj7W1H5oTCJiTdsnkhG5/view?usp=share_link'>こちら(zip)</a>．"

parse:
  myst_enable_extensions:
    - amsmath